### ISSUE TITLE
nv-hook.sh presupposed index 1 and 64 byte area

### ISSUE THREAD

**Issue by gastamper** [gastamper/dracut-tpm#2]
This should be changed to support user-specified values.

**Comment by gdownes6** [comment]
Under RHEL8 dracut appears to have issues: 1) cryptsetup is not present in /sbin and 2) the line "for question in /run/systemd/ask-password/ask.*; do" relies on ask-password to exist with content.  It exists, but the folder structure is empty.  Did you encounter and overcome this?
